Update dev from master (#746) (#747)
* Dev (#727)

* chore(): update dev from master (#694)

* Dev (#692)

* Remove specify related applications to be added to the manifest message (#663)

* Formatting related application for better display (#666)

* Delay mounting codeViewer for milliseconds to fix concurrency issue (#665)

* App's log is being used to load home page but not used as a back button (#664)

* fix(): fixes #673 (#679)

* Bug fix manifest viewer (#681)

* display empty string if manifest property's value is falsely

* Update the manifest as a key is up

* Adding id to access an editor by getElementById on a page

* Adding id to the probs and wrapping Monaco editor with a div

* Adding resize event listener when it is mounted and remove when component is destroyed

* Refactor code to make it DRY

* Applying css rules

* watching state change and reloading the editor

* Debounce helper function is added and call this function to execute update manifest

* Fixed undefined in related apps

* Putting back event listners when editor is reloaded

* Deeplinking pw aurl (#682)

* Checking if a query string is matching with pwa url or not

* Check a summited pwa url is already part of query string. if not, added it to the url

* check and generate if pwa url is already part of query string

* Overview and My Hub link is loading using query sting

* Log is used to reset and load default page

* Process query string and handling browser events

* Fixing test fail related to it should fail a bad URL

* chore(): update env to point to dev api (#685)

* Service worker page cleanup (#686)

* fix(): swap top and bottom code viewers

* style(): make the code viewer shorter for reg code

* Hide broken images (#687)

* filter broken icons from the list

* suggesion suggest to you to upload at least one image 512×512 or larger

* fix(analytics): new markers for build and features

* fix(analytics): mark exactly which worker is chosen

* fix(analytics): added marker for downloaded service worker

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* chore(): re-flip the codeviewers

* style(): shorten codeviewer

* chore(): update to use pwa-update component

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* Fix fonts (#695)

* Dev (#692)

* Remove specify related applications to be added to the manifest message (#663)

* Formatting related application for better display (#666)

* Delay mounting codeViewer for milliseconds to fix concurrency issue (#665)

* App's log is being used to load home page but not used as a back button (#664)

* fix(): fixes #673 (#679)

* Bug fix manifest viewer (#681)

* display empty string if manifest property's value is falsely

* Update the manifest as a key is up

* Adding id to access an editor by getElementById on a page

* Adding id to the probs and wrapping Monaco editor with a div

* Adding resize event listener when it is mounted and remove when component is destroyed

* Refactor code to make it DRY

* Applying css rules

* watching state change and reloading the editor

* Debounce helper function is added and call this function to execute update manifest

* Fixed undefined in related apps

* Putting back event listners when editor is reloaded

* Deeplinking pw aurl (#682)

* Checking if a query string is matching with pwa url or not

* Check a summited pwa url is already part of query string. if not, added it to the url

* check and generate if pwa url is already part of query string

* Overview and My Hub link is loading using query sting

* Log is used to reset and load default page

* Process query string and handling browser events

* Fixing test fail related to it should fail a bad URL

* chore(): update env to point to dev api (#685)

* Service worker page cleanup (#686)

* fix(): swap top and bottom code viewers

* style(): make the code viewer shorter for reg code

* Hide broken images (#687)

* filter broken icons from the list

* suggesion suggest to you to upload at least one image 512×512 or larger

* fix(analytics): new markers for build and features

* fix(analytics): mark exactly which worker is chosen

* fix(analytics): added marker for downloaded service worker

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* chore(): re-flip the codeviewers

* style(): shorten codeviewer

* chore(): update to use pwa-update component

* fix(): move to local fonts + icons

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* style(): header should be bold

* Added pwa-auth to feature store (#701)

* Dev (#692)

* Remove specify related applications to be added to the manifest message (#663)

* Formatting related application for better display (#666)

* Delay mounting codeViewer for milliseconds to fix concurrency issue (#665)

* App's log is being used to load home page but not used as a back button (#664)

* fix(): fixes #673 (#679)

* Bug fix manifest viewer (#681)

* display empty string if manifest property's value is falsely

* Update the manifest as a key is up

* Adding id to access an editor by getElementById on a page

* Adding id to the probs and wrapping Monaco editor with a div

* Adding resize event listener when it is mounted and remove when component is destroyed

* Refactor code to make it DRY

* Applying css rules

* watching state change and reloading the editor

* Debounce helper function is added and call this function to execute update manifest

* Fixed undefined in related apps

* Putting back event listners when editor is reloaded

* Deeplinking pw aurl (#682)

* Checking if a query string is matching with pwa url or not

* Check a summited pwa url is already part of query string. if not, added it to the url

* check and generate if pwa url is already part of query string

* Overview and My Hub link is loading using query sting

* Log is used to reset and load default page

* Process query string and handling browser events

* Fixing test fail related to it should fail a bad URL

* chore(): update env to point to dev api (#685)

* Service worker page cleanup (#686)

* fix(): swap top and bottom code viewers

* style(): make the code viewer shorter for reg code

* Hide broken images (#687)

* filter broken icons from the list

* suggesion suggest to you to upload at least one image 512×512 or larger

* fix(analytics): new markers for build and features

* fix(analytics): mark exactly which worker is chosen

* fix(analytics): added marker for downloaded service worker

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* chore(): re-flip the codeviewers

* style(): shorten codeviewer

* chore(): update to use pwa-update component

* chore(): update pwa-install to latest

* fix(download): shortcuts must be a real array (#698)

Otherwise, llama-pack/bubblewrap will throw the following error: `twaManifest.shortcuts.map is not a function`

* chore(): remove use of google fonts and move icons to be served locally (#700)

* chore(): update dev from master (#694)

* Dev (#692)

* Remove specify related applications to be added to the manifest message (#663)

* Formatting related application for better display (#666)

* Delay mounting codeViewer for milliseconds to fix concurrency issue (#665)

* App's log is being used to load home page but not used as a back button (#664)

* fix(): fixes #673 (#679)

* Bug fix manifest viewer (#681)

* display empty string if manifest property's value is falsely

* Update the manifest as a key is up

* Adding id to access an editor by getElementById on a page

* Adding id to the probs and wrapping Monaco editor with a div

* Adding resize event listener when it is mounted and remove when component is destroyed

* Refactor code to make it DRY

* Applying css rules

* watching state change and reloading the editor

* Debounce helper function is added and call this function to execute update manifest

* Fixed undefined in related apps

* Putting back event listners when editor is reloaded

* Deeplinking pw aurl (#682)

* Checking if a query string is matching with pwa url or not

* Check a summited pwa url is already part of query string. if not, added it to the url

* check and generate if pwa url is already part of query string

* Overview and My Hub link is loading using query sting

* Log is used to reset and load default page

* Process query string and handling browser events

* Fixing test fail related to it should fail a bad URL

* chore(): update env to point to dev api (#685)

* Service worker page cleanup (#686)

* fix(): swap top and bottom code viewers

* style(): make the code viewer shorter for reg code

* Hide broken images (#687)

* filter broken icons from the list

* suggesion suggest to you to upload at least one image 512×512 or larger

* fix(analytics): new markers for build and features

* fix(analytics): mark exactly which worker is chosen

* fix(analytics): added marker for downloaded service worker

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* chore(): re-flip the codeviewers

* style(): shorten codeviewer

* chore(): update to use pwa-update component

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* Fix fonts (#695)

* Dev (#692)

* Remove specify related applications to be added to the manifest message (#663)

* Formatting related application for better display (#666)

* Delay mounting codeViewer for milliseconds to fix concurrency issue (#665)

* App's log is being used to load home page but not used as a back button (#664)

* fix(): fixes #673 (#679)

* Bug fix manifest viewer (#681)

* display empty string if manifest property's value is falsely

* Update the manifest as a key is up

* Adding id to access an editor by getElementById on a page

* Adding id to the probs and wrapping Monaco editor with a div

* Adding resize event listener when it is mounted and remove when component is destroyed

* Refactor code to make it DRY

* Applying css rules

* watching state change and reloading the editor

* Debounce helper function is added and call this function to execute update manifest

* Fixed undefined in related apps

* Putting back event listners when editor is reloaded

* Deeplinking pw aurl (#682)

* Checking if a query string is matching with pwa url or not

* Check a summited pwa url is already part of query string. if not, added it to the url

* check and generate if pwa url is already part of query string

* Overview and My Hub link is loading using query sting

* Log is used to reset and load default page

* Process query string and handling browser events

* Fixing test fail related to it should fail a bad URL

* chore(): update env to point to dev api (#685)

* Service worker page cleanup (#686)

* fix(): swap top and bottom code viewers

* style(): make the code viewer shorter for reg code

* Hide broken images (#687)

* filter broken icons from the list

* suggesion suggest to you to upload at least one image 512×512 or larger

* fix(analytics): new markers for build and features

* fix(analytics): mark exactly which worker is chosen

* fix(analytics): added marker for downloaded service worker

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* chore(): re-flip the codeviewers

* style(): shorten codeviewer

* chore(): update to use pwa-update component

* fix(): move to local fonts + icons

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* style(): header should be bold

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* Added pwa-auth to feature store

Co-authored-by: Justin Willis <jgw9617@gmail.com>
Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>
Co-authored-by: Christian Liebel <christian.liebel@thinktecture.com>

* remove a specific character like period if it is at the end of the string (#703)

* Better layout for Feature Store documentation + removing older unused components (Geoloc, Adaptive Card and Copy clipboard).

* using generatedUrl than manifest.start_url when icons URL is prepared if it is avaliable (#717)

* Edits in manifest reflect in form (#705)

* Changing how the model is bound to make a two-way data binding (form to manifest and manifest to for)

* Handling manifest change

* Manifest is validated if it is a valid JSON format

* Debounce manifest’s API call when manifest is changed

* Fixed error generating signed APK (#691)

* Checking if the src is a valid url and get response back with the help of NodeJS proxy

* Getting a good icon from manifest. Start with 512 by 512 and if 512 doesn't exist, loop through all icons

* Refactored handleTWA function to get good icon before calling generateSignedApkZip api and display error properly

* Excluding uploaded icons which has data:image value to src property

* Detecting when an image fails to load

* Ensuring promise is resolves

* Updated pwa-auth component with apple info (#725)

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>
Co-authored-by: Judah Gabriel Himango <judahgabriel@gmail.com>
Co-authored-by: Christian Liebel <christian.liebel@thinktecture.com>
Co-authored-by: David Rousset <davrous@microsoft.com>

* merge

* chore(): update starter to latest (#743)

* Starter drop down (#745)

* feat(): dropdown for starter flow

* feat(): updated design

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>
Co-authored-by: Judah Gabriel Himango <judahgabriel@gmail.com>
Co-authored-by: Christian Liebel <christian.liebel@thinktecture.com>
Co-authored-by: David Rousset <davrous@microsoft.com>

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>
Co-authored-by: Judah Gabriel Himango <judahgabriel@gmail.com>
Co-authored-by: Christian Liebel <christian.liebel@thinktecture.com>
Co-authored-by: David Rousset <davrous@microsoft.com>