Added pwa-auth to feature store (#701)
* Dev (#692)

* Remove specify related applications to be added to the manifest message (#663)

* Formatting related application for better display (#666)

* Delay mounting codeViewer for milliseconds to fix concurrency issue (#665)

* App's log is being used to load home page but not used as a back button (#664)

* fix(): fixes #673 (#679)

* Bug fix manifest viewer (#681)

* display empty string if manifest property's value is falsely

* Update the manifest as a key is up

* Adding id to access an editor by getElementById on a page

* Adding id to the probs and wrapping Monaco editor with a div

* Adding resize event listener when it is mounted and remove when component is destroyed

* Refactor code to make it DRY

* Applying css rules

* watching state change and reloading the editor

* Debounce helper function is added and call this function to execute update manifest

* Fixed undefined in related apps

* Putting back event listners when editor is reloaded

* Deeplinking pw aurl (#682)

* Checking if a query string is matching with pwa url or not

* Check a summited pwa url is already part of query string. if not, added it to the url

* check and generate if pwa url is already part of query string

* Overview and My Hub link is loading using query sting

* Log is used to reset and load default page

* Process query string and handling browser events

* Fixing test fail related to it should fail a bad URL

* chore(): update env to point to dev api (#685)

* Service worker page cleanup (#686)

* fix(): swap top and bottom code viewers

* style(): make the code viewer shorter for reg code

* Hide broken images (#687)

* filter broken icons from the list

* suggesion suggest to you to upload at least one image 512×512 or larger

* fix(analytics): new markers for build and features

* fix(analytics): mark exactly which worker is chosen

* fix(analytics): added marker for downloaded service worker

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* chore(): re-flip the codeviewers

* style(): shorten codeviewer

* chore(): update to use pwa-update component

* chore(): update pwa-install to latest

* fix(download): shortcuts must be a real array (#698)

Otherwise, llama-pack/bubblewrap will throw the following error: `twaManifest.shortcuts.map is not a function`

* chore(): remove use of google fonts and move icons to be served locally (#700)

* chore(): update dev from master (#694)

* Dev (#692)

* Remove specify related applications to be added to the manifest message (#663)

* Formatting related application for better display (#666)

* Delay mounting codeViewer for milliseconds to fix concurrency issue (#665)

* App's log is being used to load home page but not used as a back button (#664)

* fix(): fixes #673 (#679)

* Bug fix manifest viewer (#681)

* display empty string if manifest property's value is falsely

* Update the manifest as a key is up

* Adding id to access an editor by getElementById on a page

* Adding id to the probs and wrapping Monaco editor with a div

* Adding resize event listener when it is mounted and remove when component is destroyed

* Refactor code to make it DRY

* Applying css rules

* watching state change and reloading the editor

* Debounce helper function is added and call this function to execute update manifest

* Fixed undefined in related apps

* Putting back event listners when editor is reloaded

* Deeplinking pw aurl (#682)

* Checking if a query string is matching with pwa url or not

* Check a summited pwa url is already part of query string. if not, added it to the url

* check and generate if pwa url is already part of query string

* Overview and My Hub link is loading using query sting

* Log is used to reset and load default page

* Process query string and handling browser events

* Fixing test fail related to it should fail a bad URL

* chore(): update env to point to dev api (#685)

* Service worker page cleanup (#686)

* fix(): swap top and bottom code viewers

* style(): make the code viewer shorter for reg code

* Hide broken images (#687)

* filter broken icons from the list

* suggesion suggest to you to upload at least one image 512×512 or larger

* fix(analytics): new markers for build and features

* fix(analytics): mark exactly which worker is chosen

* fix(analytics): added marker for downloaded service worker

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* chore(): re-flip the codeviewers

* style(): shorten codeviewer

* chore(): update to use pwa-update component

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* Fix fonts (#695)

* Dev (#692)

* Remove specify related applications to be added to the manifest message (#663)

* Formatting related application for better display (#666)

* Delay mounting codeViewer for milliseconds to fix concurrency issue (#665)

* App's log is being used to load home page but not used as a back button (#664)

* fix(): fixes #673 (#679)

* Bug fix manifest viewer (#681)

* display empty string if manifest property's value is falsely

* Update the manifest as a key is up

* Adding id to access an editor by getElementById on a page

* Adding id to the probs and wrapping Monaco editor with a div

* Adding resize event listener when it is mounted and remove when component is destroyed

* Refactor code to make it DRY

* Applying css rules

* watching state change and reloading the editor

* Debounce helper function is added and call this function to execute update manifest

* Fixed undefined in related apps

* Putting back event listners when editor is reloaded

* Deeplinking pw aurl (#682)

* Checking if a query string is matching with pwa url or not

* Check a summited pwa url is already part of query string. if not, added it to the url

* check and generate if pwa url is already part of query string

* Overview and My Hub link is loading using query sting

* Log is used to reset and load default page

* Process query string and handling browser events

* Fixing test fail related to it should fail a bad URL

* chore(): update env to point to dev api (#685)

* Service worker page cleanup (#686)

* fix(): swap top and bottom code viewers

* style(): make the code viewer shorter for reg code

* Hide broken images (#687)

* filter broken icons from the list

* suggesion suggest to you to upload at least one image 512×512 or larger

* fix(analytics): new markers for build and features

* fix(analytics): mark exactly which worker is chosen

* fix(analytics): added marker for downloaded service worker

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* chore(): re-flip the codeviewers

* style(): shorten codeviewer

* chore(): update to use pwa-update component

* fix(): move to local fonts + icons

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* style(): header should be bold

Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>

* Added pwa-auth to feature store

Co-authored-by: Justin Willis <jgw9617@gmail.com>
Co-authored-by: TesheG <60520041+TesheG@users.noreply.github.com>
Co-authored-by: Christian Liebel <christian.liebel@thinktecture.com>